package main

import (
	"fmt"
	"log"

	"github.com/reclaimprotocol/xpath-go"
)

func main() {
	htmlContent := `<html><body><div class='primary inactive'>Item 3</div></body></html>`

	fmt.Println("=== TESTING COMPLEX BOOLEAN STEP BY STEP ===")
	fmt.Println()

	// Test individual parts that would be generated by the recursive split
	fmt.Println("Testing individual recursive parts:")

	// Left side of first split
	result1, err := xpath.Query("//div[contains(@class, 'primary')]", htmlContent)
	if err != nil {
		log.Fatal(err)
	}
	fmt.Printf("LEFT: contains(@class, 'primary'): %d results\n", len(result1))

	// Right side of first split (should be evaluated recursively)
	result2, err := xpath.Query("//div[contains(@class, 'active') and not(contains(@class, 'inactive'))]", htmlContent)
	if err != nil {
		log.Fatal(err)
	}
	fmt.Printf("RIGHT: contains(@class, 'active') and not(contains(@class, 'inactive')): %d results\n", len(result2))

	// Test the second split that should happen in the recursive call
	result3, err := xpath.Query("//div[contains(@class, 'active')]", htmlContent)
	if err != nil {
		log.Fatal(err)
	}
	fmt.Printf("RIGHT LEFT: contains(@class, 'active'): %d results\n", len(result3))

	result4, err := xpath.Query("//div[not(contains(@class, 'inactive'))]", htmlContent)
	if err != nil {
		log.Fatal(err)
	}
	fmt.Printf("RIGHT RIGHT: not(contains(@class, 'inactive')): %d results\n", len(result4))

	fmt.Println("\nExpected logic:")
	fmt.Println("LEFT (1) AND RIGHT (0) = 0")
	fmt.Println("But we're getting 1 result total, so RIGHT is returning 1 instead of 0")
}
